### ISSUE TITLE
Causes a build error when used with Xamarin.GooglePlayServices.Location v71.1600.0

### ISSUE THREAD

**Issue by BrianDT** [thefex/Xamarin.Bindings.AdvancedRecyclerView#11]
The existing release that references the android v26 libraries and significantly Xamarin.Build.Download  0.4.7 causes a build error when included in a project with Xamarin.GooglePlayServices.Location v71.1600.0
A release referencing the v28 libraries and Xamarin.Build.Download  0.4.11 might be more compatible.
The issue can be reproduced by creating a new app based on the default template, and adding this nugget package and Xamarin.GooglePlayServices.Location v71.1600.0 and then compiling.
```
1>------ Build started: Project: TestLevel71GooglePackages, Configuration: Debug Any CPU ------
1>C:\...\.nuget\packages\xamarin.build.download\0.4.11\build\Xamarin.Build.Download.targets(137,3): error MSB4018: The "XamarinBuildAndroidAarProguardConfigs" task failed unexpectedly.
1>C:\ ...\.nuget\packages\xamarin.build.download\0.4.11\build\Xamarin.Build.Download.targets(137,3): error MSB4018: System.IO.InvalidDataException: End of Central Directory record could not be found.
1>C:\ ...\.nuget\packages\xamarin.build.download\0.4.11\build\Xamarin.Build.Download.targets(137,3): error MSB4018:    at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
1>C:\ ...\.nuget\packages\xamarin.build.download\0.4.11\build\Xamarin.Build.Download.targets(137,3): error MSB4018:    at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
1>C:\ ...\.nuget\packages\xamarin.build.download\0.4.11\build\Xamarin.Build.Download.targets(137,3): error MSB4018:    at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
1>C:\ ...\.nuget\packages\xamarin.build.download\0.4.11\build\Xamarin.Build.Download.targets(137,3): error MSB4018:    at Xamarin.Build.Download.XamarinBuildAndroidAarProguardConfigs.Execute()
1>C:\ ...\.nuget\packages\xamarin.build.download\0.4.11\build\Xamarin.Build.Download.targets(137,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\ ...\.nuget\packages\xamarin.build.download\0.4.11\build\Xamarin.Build.Download.targets(137,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```
While this is not strictly an issue with this package, and update might help provide a short term workaround the problem

**Comment by thefex** [comment]
I have a project with Location v71.1600 and it works . 
Please create reproduction sample
